let g:ex_toolkit_path = '~/.toolkit'
source ~\.vimrc_ex
au BufNewFile,BufEnter * set cpoptions+=d
"nnoremap <unique> <Leader>bd :call exUtility#Kwbd(1)<CR>
let g:exES_ImageViewer='/usr/bin/kview'

source ~/.vim/my-settings.vim
